[package]
name = "dirsync"
version = "0.1.0"
edition = "2021"

[dependencies]
notify = { version = "8.0.0" }
clap = { version = "4.5.8", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
dirs = { version = "6.0.0" }
serde_json = { version = "1.0.140" }
